"""coverage runs and cells

Revision ID: 00ad907f16d1
Revises: eaf4c8497285
Create Date: 2026-09-01 01:19:09.896218

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00ad907f16d1'
down_revision: str | Sequence[str] | None = 'eaf4c8497285'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_runs',
    sa.Column('boundary_id', sa.Uuid(), nullable=True),
    sa.Column('boundary_name', sa.String(length=200), nullable=True),
    sa.Column('hex_edge_m', sa.Float(), nullable=False),
    sa.Column('covered_threshold', sa.Float(), nullable=False),
    sa.Column('gap_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_cells', sa.Integer(), nullable=False),
    sa.Column('installed_coverage_pct', sa.Float(), nullable=False),
    sa.Column('effective_coverage_pct', sa.Float(), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('online_camera_count', sa.Integer(), nullable=False),
    sa.Column('assumed_omnidirectional_count', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['admin_boundaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_cells',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('installed_fraction', sa.Float(), nullable=False),
    sa.Column('effective_fraction', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['coverage_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coverage_cells_geom', 'coverage_cells', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_coverage_cells_run', 'coverage_cells', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coverage_cells_run', table_name='coverage_cells')
    op.drop_index('ix_coverage_cells_geom', table_name='coverage_cells', postgresql_using='gist')
    op.drop_table('coverage_cells')
    op.drop_table('coverage_runs')
    # ### end Alembic commands ###
