"""core registry schema

Revision ID: 09819d74d6f6
Revises: 
Create Date: 2026-08-31 20:04:22.855630

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09819d74d6f6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dept_type', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('cameras',
    sa.Column('camera_uid', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('operator_department_id', sa.Uuid(), nullable=True),
    sa.Column('external_camera_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('camera_type', sa.String(length=32), nullable=False),
    sa.Column('camera_technology', sa.String(length=16), nullable=False),
    sa.Column('azimuth_deg', sa.Float(), nullable=True),
    sa.Column('fov_deg', sa.Float(), nullable=True),
    sa.Column('range_m', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('has_night_vision', sa.Boolean(), nullable=True),
    sa.Column('connectivity', sa.String(length=16), nullable=False),
    sa.Column('storage_type', sa.String(length=32), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('ownership_class', sa.String(length=16), nullable=False),
    sa.Column('site_type', sa.String(length=32), nullable=False),
    sa.Column('amc_vendor', sa.String(length=200), nullable=True),
    sa.Column('amc_expiry_date', sa.Date(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.String(length=16), nullable=False),
    sa.Column('status_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('field_mapping_version', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['operator_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'external_camera_id', name='uq_camera_dept_external')
    )
    op.create_index(op.f('ix_cameras_camera_uid'), 'cameras', ['camera_uid'], unique=True)
    op.create_index(op.f('ix_cameras_department_id'), 'cameras', ['department_id'], unique=False)
    op.create_index('ix_cameras_location', 'cameras', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_cameras_metadata', 'cameras', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_cameras_status_since', 'cameras', ['current_status', 'status_since'], unique=False)
    op.create_table('field_mappings',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'version')
    )
    op.create_index(op.f('ix_field_mappings_department_id'), 'field_mappings', ['department_id'], unique=False)
    op.create_table('stream_endpoints',
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('codec', sa.String(length=16), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('reachability', sa.String(length=16), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('credential_ref', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probe_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_endpoints_camera_id'), 'stream_endpoints', ['camera_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_endpoints_camera_id'), table_name='stream_endpoints')
    op.drop_table('stream_endpoints')
    op.drop_index(op.f('ix_field_mappings_department_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    op.drop_index('ix_cameras_status_since', table_name='cameras')
    op.drop_index('ix_cameras_metadata', table_name='cameras', postgresql_using='gin')
    op.drop_index('ix_cameras_location', table_name='cameras', postgresql_using='gist')
    op.drop_index(op.f('ix_cameras_department_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_uid'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
