"""vocabulary terms, connectors, credentials, place aliases

Revision ID: 508b998c3871
Revises: c233a8d764b2
Create Date: 2026-09-01 02:17:51.883212

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '508b998c3871'
down_revision: str | Sequence[str] | None = 'c233a8d764b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_name'), 'credentials', ['name'], unique=True)
    op.create_table('vocabulary_terms',
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('coverage_range_m', sa.Float(), nullable=True),
    sa.Column('coverage_fov_deg', sa.Float(), nullable=True),
    sa.Column('is_omnidirectional', sa.Boolean(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'code', name='uq_vocab_dimension_code')
    )
    op.create_index('ix_vocab_dimension_active', 'vocabulary_terms', ['dimension', 'is_active'], unique=False)
    op.create_index(op.f('ix_vocabulary_terms_dimension'), 'vocabulary_terms', ['dimension'], unique=False)
    op.create_table('place_aliases',
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('boundary_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['admin_boundaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_aliases_alias'), 'place_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_place_aliases_boundary_id'), 'place_aliases', ['boundary_id'], unique=False)
    op.create_table('source_connectors',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_connectors_code'), 'source_connectors', ['code'], unique=True)
    op.create_index(op.f('ix_source_connectors_department_id'), 'source_connectors', ['department_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_connectors_department_id'), table_name='source_connectors')
    op.drop_index(op.f('ix_source_connectors_code'), table_name='source_connectors')
    op.drop_table('source_connectors')
    op.drop_index(op.f('ix_place_aliases_boundary_id'), table_name='place_aliases')
    op.drop_index(op.f('ix_place_aliases_alias'), table_name='place_aliases')
    op.drop_table('place_aliases')
    op.drop_index(op.f('ix_vocabulary_terms_dimension'), table_name='vocabulary_terms')
    op.drop_index('ix_vocab_dimension_active', table_name='vocabulary_terms')
    op.drop_table('vocabulary_terms')
    op.drop_index(op.f('ix_credentials_name'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
