"""district located camera count

Revision ID: c233a8d764b2
Revises: 00ad907f16d1
Create Date: 2026-09-01 01:52:18.889017

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c233a8d764b2'
down_revision: str | Sequence[str] | None = '00ad907f16d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverage_runs', sa.Column(
            'district_located_camera_count',
            sa.Integer(),
            nullable=False,
            # Existing rows predate this column; without a server default the
            # ALTER fails on any table that already holds data.
            server_default='0',
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coverage_runs', 'district_located_camera_count')
    # ### end Alembic commands ###
