"""admin boundaries

Revision ID: c83d8d502d37
Revises: 09819d74d6f6
Create Date: 2026-08-31 21:56:34.622245

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c83d8d502d37'
down_revision: str | Sequence[str] | None = '09819d74d6f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_boundaries',
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_boundaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_boundaries_geom', 'admin_boundaries', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_admin_boundaries_name'), 'admin_boundaries', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_boundaries_name'), table_name='admin_boundaries')
    op.drop_index('ix_admin_boundaries_geom', table_name='admin_boundaries', postgresql_using='gist')
    op.drop_table('admin_boundaries')
    # ### end Alembic commands ###
