"""SQL definitions for the camera-footprint functions.

These live in a module rather than being buried inside the migration body so that the
migration and the test fixture install byte-identical definitions from one source. The
alternative -- having `tests/conftest.py` scrape the SQL back out of the migration file
with a regex -- couples the tests to the migration's filename, its formatting and the
process working directory, and breaks silently the first time either changes.

Keeping repeatable DDL in a versioned module is safe here precisely because these are
`CREATE OR REPLACE FUNCTION` statements with no data dependency: replaying the whole
migration history applies whatever definition the module currently holds, and the end
state is the same either way. That would *not* be safe for table DDL, which is why only
the function bodies live here and the tables stay in autogenerated migrations.
"""

CAMERA_SECTOR = """
CREATE OR REPLACE FUNCTION camera_sector(
    loc geography,
    azimuth double precision,
    fov double precision,
    radius_m double precision,
    steps integer DEFAULT 24
) RETURNS geography AS $$
DECLARE
    ring geometry;
BEGIN
    -- ST_Project takes an azimuth in radians measured clockwise from north, which is
    -- exactly how a camera bearing is recorded, so no coordinate conversion is needed.
    SELECT ST_MakeLine(pt ORDER BY step) INTO ring
    FROM (
        SELECT step,
               ST_Project(
                   loc,
                   radius_m,
                   radians(azimuth - fov / 2.0 + (fov * step::double precision / steps))
               )::geometry AS pt
        FROM generate_series(0, steps) AS step
    ) arc;

    -- Close the wedge by returning to the camera position at both ends.
    ring := ST_AddPoint(ring, loc::geometry, 0);
    ring := ST_AddPoint(ring, loc::geometry);

    RETURN ST_MakePolygon(ST_SetSRID(ring, 4326))::geography;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
"""

CAMERA_FOOTPRINT = """
CREATE OR REPLACE FUNCTION camera_footprint(
    loc geography,
    cam_type text,
    azimuth double precision,
    fov double precision,
    range_m double precision
) RETURNS geography AS $$
    -- Geometry defaults come from the vocabulary_terms row for this camera type,
    -- not from a CASE expression listing vendor words. A department running a
    -- camera type nobody anticipated adds a row with its own range and field of
    -- view; the gap analysis then models it correctly without a code change.
    --
    -- A camera is omnidirectional when its term says so, or when it has no
    -- recorded bearing. The latter OVERSTATES coverage, which is why the run
    -- counts those separately so the report can disclose it.
    WITH term AS (
        SELECT coverage_range_m, coverage_fov_deg, is_omnidirectional
        FROM vocabulary_terms
        WHERE dimension = 'camera_type' AND code = cam_type AND is_active
        LIMIT 1
    ),
    resolved AS (
        SELECT
            COALESCE(range_m, (SELECT coverage_range_m FROM term), 100.0) AS r,
            COALESCE(fov, (SELECT coverage_fov_deg FROM term), 90.0)      AS f,
            COALESCE((SELECT is_omnidirectional FROM term), false)        AS omni
    )
    SELECT CASE
        WHEN resolved.omni
          OR azimuth IS NULL
          OR resolved.f >= 360
        THEN ST_Buffer(loc, resolved.r)
        ELSE camera_sector(loc, azimuth, resolved.f, resolved.r)
    END
    FROM resolved
$$ LANGUAGE sql STABLE;
"""

# Applied in order; camera_footprint calls camera_sector, so the sector goes first.
COVERAGE_FUNCTIONS = (CAMERA_SECTOR, CAMERA_FOOTPRINT)

DROP_COVERAGE_FUNCTIONS = (
    "DROP FUNCTION IF EXISTS camera_footprint("
    "geography, text, double precision, double precision, double precision)",
    "DROP FUNCTION IF EXISTS camera_sector("
    "geography, double precision, double precision, double precision, integer)",
)
