"""SQL definitions for the camera-footprint functions.

These live in a module rather than being buried inside the migration body so that the
migration and the test fixture install byte-identical definitions from one source. The
alternative -- having `tests/conftest.py` scrape the SQL back out of the migration file
with a regex -- couples the tests to the migration's filename, its formatting and the
process working directory, and breaks silently the first time either changes.

Keeping repeatable DDL in a versioned module is safe here precisely because these are
`CREATE OR REPLACE FUNCTION` statements with no data dependency: replaying the whole
migration history applies whatever definition the module currently holds, and the end
state is the same either way. That would *not* be safe for table DDL, which is why only
the function bodies live here and the tables stay in autogenerated migrations.
"""

CAMERA_SECTOR = """
CREATE OR REPLACE FUNCTION camera_sector(
    loc geography,
    azimuth double precision,
    fov double precision,
    radius_m double precision,
    steps integer DEFAULT 24
) RETURNS geography AS $$
DECLARE
    ring geometry;
BEGIN
    -- ST_Project takes an azimuth in radians measured clockwise from north, which is
    -- exactly how a camera bearing is recorded, so no coordinate conversion is needed.
    SELECT ST_MakeLine(pt ORDER BY step) INTO ring
    FROM (
        SELECT step,
               ST_Project(
                   loc,
                   radius_m,
                   radians(azimuth - fov / 2.0 + (fov * step::double precision / steps))
               )::geometry AS pt
        FROM generate_series(0, steps) AS step
    ) arc;

    -- Close the wedge by returning to the camera position at both ends.
    ring := ST_AddPoint(ring, loc::geometry, 0);
    ring := ST_AddPoint(ring, loc::geometry);

    RETURN ST_MakePolygon(ST_SetSRID(ring, 4326))::geography;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
"""

CAMERA_FOOTPRINT = """
CREATE OR REPLACE FUNCTION camera_footprint(
    loc geography,
    cam_type text,
    azimuth double precision,
    fov double precision,
    range_m double precision
) RETURNS geography AS $$
    SELECT CASE
        -- PTZ and dome cameras sweep, so treat them as omnidirectional. A fixed camera
        -- with no recorded bearing also falls back to a circle; the report flags those
        -- rows as "assumed omnidirectional" rather than silently overstating coverage.
        WHEN cam_type IN ('ptz', 'dome')
          OR azimuth IS NULL
          OR fov IS NULL
          OR fov >= 360
        THEN ST_Buffer(
            loc,
            COALESCE(range_m, CASE WHEN cam_type IN ('ptz', 'dome') THEN 250 ELSE 100 END)
        )
        ELSE camera_sector(
            loc, azimuth, fov,
            COALESCE(range_m, CASE WHEN cam_type = 'anpr' THEN 60 ELSE 100 END)
        )
    END
$$ LANGUAGE sql IMMUTABLE;
"""

# Applied in order; camera_footprint calls camera_sector, so the sector goes first.
COVERAGE_FUNCTIONS = (CAMERA_SECTOR, CAMERA_FOOTPRINT)

DROP_COVERAGE_FUNCTIONS = (
    "DROP FUNCTION IF EXISTS camera_footprint("
    "geography, text, double precision, double precision, double precision)",
    "DROP FUNCTION IF EXISTS camera_sector("
    "geography, double precision, double precision, double precision, integer)",
)
